### ISSUE TITLE
Filter out image file but not count 

### ISSUE THREAD

**Issue by waitingkuo** [PuerkitoBio/gocrawl#36]
In Filter() I can only get the URL. I'd detect whether it's image by Context-Type. But when I get the Context-Type, that page has already been counted in. Is it possible to do something like: "Crawl first 100 pages with Context-Type equals to text/html" ?

**Comment by PuerkitoBio** [comment]
I don't think it's possible, gocrawl's API is pretty horrible if you ask me... I'd suggest trying fetchbot instead.

**Comment by waitingkuo** [comment]
Thanks, i'll take a look at fetchbot
