### ISSUE TITLE
Panic Error When crawler

### ISSUE THREAD

**Issue by tommoholmes10** [PuerkitoBio/gocrawl#38]
I have trouble, when gocrawler run but suddenly it's stop error message is ``Get link: EOF
exit status 1
``
when I check this url, this web is working

and Why my gocrawler visit the same link
this is my config

```go
const (
  DEPTH = 0
)
opts := gocrawl.NewOptions(new(ExampleExtender))
  opts.CrawlDelay = 10
  opts.LogFlags = gocrawl.LogNone
  opts.RobotUserAgent = "Google"
  opts.UserAgent ="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0"
  c := gocrawl.NewCrawlerWithOptions(opts)
  c.Run(gocrawl.S{
  "https://www.someurl1.com/": DEPTH, 
  "http://www.someurl2.co.id/" : DEPTH, 
  "http://www.someurl3.co.id/" : DEPTH, 
  "https://www.someurl4.com/": DEPTH, 
  "https://www.someurl5.com/": DEPTH, 
  "http://www.someurl6.com/": DEPTH, 
  "https://www.someurl7.com/": DEPTH, 
  "http://someurl8.com/": DEPTH, 
  "http://www.someurl9.com/": DEPTH, 
  "http://www.someurl10.com/": DEPTH, 
  "http://www.someurl11.com/": DEPTH,
  })
```

**Comment by PuerkitoBio** [comment]
EOF errors can happen with network calls, this is to be expected when crawling websites, you should design your app to handle this.

I don't have enough details for your 2nd question.

**Comment by tommoholmes** [comment]
How I can handle it. Give me example please

Our 2nd question is why gocrawler visit page morethan 1 link in the same.
Example: gocrawler visit this google.com morethan 1

**Comment by tommoholmes10** [comment]
How I can handle it. Give me example please
