### ISSUE TITLE
User-Agent is lost on redirect

### ISSUE THREAD

**Issue by benjojo** [PuerkitoBio/gocrawl#42]
While looking though my logs today I found this

```
blog.benjojo.co.uk 54.166.28.206 - - 2015-09-11T14:35:23Z "GET /robots.txt HTTP/1.1" 301 377 "" "Googlebot (gocrawl v0.4)" 2244194f10332390
blog.benjojo.co.uk 54.166.28.206 - - 2015-09-11T14:35:25Z "GET /robots.txt HTTP/1.1" 200 771 "http://blog.benjojo.co.uk/robots.txt" "Go 1.1 package http" 22441959ce3523c0
```

So I found this repo though the first User-Agent, but the 2nd one shows that you are now putting back in the user-agent on the [CheckRedirect](https://godoc.org/net/http#Client) part of the HTTP request.

This can lead to confusion and blocking from systems that kill default user agents due to abuse associated with them

**Comment by PuerkitoBio** [comment]
Thanks, that is indeed a bug, I'll look into it.
