### ISSUE TITLE
Crawl timeout

### ISSUE THREAD

**Issue by juliend2** [PuerkitoBio/gocrawl#44]
I would like the crawls to stop after 1 hour, because some websites have an infinite amount of URLs.
So I think it would be great to have a `CrawlTimeout` option, or an Extender function like `ShouldFinishCrawl() bool`.

Note: I use it with SameHostOnly = true, to crawl only one site.

**Comment by PuerkitoBio** [comment]
Hi Julien,

You can set the `MaxVisits` option if you know how many you want to visit, and of course you can stop returning URLs to visit in your `Visit` method, so you stop adding new links at some point.

I believe you can also call Crawler.Stop() after some time? I'm not sure how well that works to be honest, haven't used gocrawl in a long time.

HTH,
Martin

**Comment by juliend2** [comment]
Thanks for your quick response!
I tried your solution of returning false from Visit (I also tried Filter), but it continues to loop. 

How can I access the `Crawler` instance from `Visit` or `Filter` method, so I can call `Stop()` on it ?

Many thanks for gocrawl, I love it so far!

**Comment by juliend2** [comment]
Ah, I see now; it's the value returned by `NewCrawlerWithOptions(opts)`. Thanks!

**Comment by juliend2** [comment]
I ended up doing this:

```go
	c := gocrawl.NewCrawlerWithOptions(opts)
        // New code:
	go func(crawler *gocrawl.Crawler) {
		time.Sleep(1 * time.Minute)
		crawler.Stop()
	}(c)
        // end new code
	c.Run(baseUrl)
```
