### ISSUE TITLE
Support for base tag

### ISSUE THREAD

**Issue by juliend2** [PuerkitoBio/gocrawl#45]
I don't know if this issue belongs in [purell](https://github.com/juliend2/purell) (if so, please let me know), but I think it would be nice to support sites that use the `<base>` tag. An example of such practice can be found in [my own website](http://www.juliendesrosiers.com/)'s HTML.

Because as it is right now, if I crawl the aforementioned website with gocrawl, it won't use the `base`'s `href` value to properly treat the relative tags it will see, example:

If the crawler is currently in http://www.juliendesrosiers.com/2012/11/20/wordpress-plugins-for-complex-websites , it will see the portfolio's relative link (`href="portfolio"`) and try to go [here](http://www.juliendesrosiers.com/2012/11/20/portfolio) instead of [here](http://www.juliendesrosiers.com/portfolio).

I would like to create a pull request for this feature, so if you have any suggestion for the implementation, I'll take it. Thanks!

**Comment by PuerkitoBio** [comment]
Bonjour Julien,

Good catch, I think it should be done in `worker.go`, in `processLinks` (if there's a custom `Visit` method that processes the links itself, then it would be its responsibility to correctly resolve relative URLs).

You can grab the `base` element with the Goquery document and combine it with the relative URLs found in the document.

Note that a `base` element may be relative itself, so it should still be resolved in the context of the document's URL.

Thanks,
Martin

**Comment by juliend2** [comment]
Thanks for your response!

Here is my PR: https://github.com/PuerkitoBio/gocrawl/pull/46
