### ISSUE TITLE
Change User-agent to look for in robots.txt records

### ISSUE THREAD

**Issue by ranvis** [PuerkitoBio/gocrawl#52]
http://www.robotstxt.org/norobots-rfc.txt 3.2.1 says robots identify themselves as simple product token.
For gocrawl, the token for default user-agent would be 'gocrawl'.
Site owners may not like using "Googlebot (gocrawl vM.m)" as they should include every version number if they want to control robot's behavior.

**Comment by PuerkitoBio** [comment]
See #51 and #41 . Basically - this is just a default, it can and should (as mentioned in the readme) be set to something else by the user of the package. I'll make this more obvious in the doc.

**Comment by PuerkitoBio** [comment]
Updated the docs and example to make that stand out.
