### ISSUE TITLE
handleBaseTag dies hard when any of the Parse fails.

### ISSUE THREAD

**Issue by tmatsuo** [PuerkitoBio/gocrawl#56]
https://github.com/PuerkitoBio/gocrawl/blob/639cda895f34579b33a74d068cf4c69bb1777248/worker.go#L361

It does not check errors.

**Comment by PuerkitoBio** [comment]
Indeed, thanks for reporting.

**Comment by tmatsuo** [comment]
Thanks for the quick fix!
