### ISSUE TITLE
Concurent fetching on the same host

### ISSUE THREAD

**Issue by puzanov** [PuerkitoBio/gocrawl#58]
Hello!

Is it possible to make crawler concurrent while fetching pages from the same host? I need to crawl one host and it has 100k pages. Existing implementation creates one worker with consistent fetching, one by one, this is too slow.

Any advice? I can't find where I can configure that. Please help where I can patch the code for that.

**Comment by puzanov** [comment]
`				if ctx.IsRobotsURL() {
					w.requestRobotsTxt(ctx)
				} else if w.isAllowedPerRobotsPolicies(ctx.url) {
					w.requestURL(ctx, ctx.HeadBeforeGet)
				} else {
					// Must still notify Crawler that this URL was processed, although not visited
					w.opts.Extender.Disallowed(ctx)
					w.sendResponse(ctx, false, nil, false)
				}
`
This is from worker.go and there is no concurrent feature. So as I see concurrency is made only for workers which can handle one host, not for fetching urls?

**Comment by PuerkitoBio** [comment]
Hello,

Gocrawl's design is based on robots.txt compliance, and as such, it is designed to allow a single request at a time for a given host.

If you don't have/want that constraint, it is probably enough to just launch N goroutines that send GET requests (e.g. read from a channel) regardless of host/robots.txt policies, without the need for a package such as this.

HTH,
Martin

**Comment by puzanov** [comment]
OK, thanks in advise.
