### ISSUE TITLE
Reduce memory usage?

### ISSUE THREAD

**Issue by SimplySerenity** [PuerkitoBio/gocrawl#65]
So far I've tried keeping all my data in a DB, and setting the queue buffer size down to 20. While both of these certainly helped, on pages with a LOT of links the memory usage just climbs and climbs. 

My most recent test has been running for ~10 minutes and is already using 400 MB of ram and counting!

**Comment by mna** [comment]
Hello Kyle,

How do you monitor the memory usage? Is it with `top` or some similar outside-the-process command? If so, you may be looking at the virtual memory reserved for the process, which isn't necessarily the memory used by the process. E.g. if I run the example command in the gocrawl repo (I'll update it on github in a moment, as it requires a change in the start address), it uses 800MB of virtual memory, but between 10-20MB of resident memory.

If you can (and presuming that's not already what you do), you should monitor from inside your process, by calling `runtime.ReadMemStats`. E.g. for the example command, the `MemStats.HeapAlloc` field is pretty consistently between 5-10 MB for me (rising and dropping along with the GC runs).

If you are already running `runtime.ReadMemStats` from inside your process, then make sure you look at `HeapAlloc`, which reflects the current memory usage, not `TotalAlloc` which always increments (and does not represent the current usage). So if you look at `HeapAlloc`, I guess you could see it grow to big numbers depending on number of workers, size of page to parse, etc., but it should vary and shrink back to lower numbers when the GC runs and smaller pages are processed.

Hope that helps,
Martin

**Comment by mna** [comment]
Yes the resident memory (RES column) is representative of the actual usage of the process. I'd be surprised if the binary couldn't run on a 1GB server if it is dedicated to running that command, unless there's a memory leak/GC issue (i.e. you hold on to all processed pages somehow or something like that).

If you still have issues running your command on 1GB, I'd suggest you add `runtime.ReadMemStats` at some regular intervals (e.g. after processing N urls) and see if the `HeapAlloc` goes back down (as would be expected) once in a while.

**Comment by SimplySerenity** [comment]
Thank you for your help, I'll close this for now and reopen it if needed.
