### ISSUE TITLE
How to crawl a site that has `<meta name="robots" content="noindex, nofollow">` ?

### ISSUE THREAD

**Issue by juliend2** [PuerkitoBio/gocrawl#66]
Here is my example code:

```go
package main

import (
	"fmt"
	"github.com/PuerkitoBio/gocrawl"
	"time"
)

// Create the Extender implementation, based on the gocrawl-provided DefaultExtender,
// because we don't want/need to override all methods.
type ExampleExtender struct {
	gocrawl.DefaultExtender // Will use the default implementation of all but Visit() and Filter()
}

func ExampleCrawl(baseUrl string) {
	// Set custom options
	opts := gocrawl.NewOptions(new(ExampleExtender))
	opts.CrawlDelay = 1 * time.Second
	opts.LogFlags = gocrawl.LogAll

	c := gocrawl.NewCrawlerWithOptions(opts)
	c.Run(baseUrl)

}

func (this *ExampleExtender) RequestRobots(ctx *gocrawl.URLContext, robotAgent string) (data []byte, request bool) {
	fmt.Println("Disobey robots")
	return []byte(""), false // as if there was no robots.txt at all to obey
}

func main() {
	opts := gocrawl.NewOptions(new(ExampleExtender))
	opts.CrawlDelay = 1 * time.Second
	opts.LogFlags = gocrawl.LogAll
	c := gocrawl.NewCrawlerWithOptions(opts)
	c.Run("http://example.com/")
}
```

I changed the URL because it's secret. But the only thing that seem to prevent me from crawling that site is the `<meta name="robots" content="noindex, nofollow">`. It also has this `robots.txt`, but as you can see above, I ignore it:

```
User-agent: *
Disallow: /
```

So, apart from the robots.txt file, is there something in gocrawl or its dependencies that could stop the crawl if it finds a `<meta name="robots" content="noindex, nofollow">` tag the HTML response?

Thanks in advance, and thank you for gocrawl as well, BTW!

**Comment by mna** [comment]
Hello Julien,

It's been a while since I've looked at that code, but as far as I remember, the crawler doesn't take that meta tag into account. I tried adding that tag to some of the test pages and it didn't affect the results. Are you sure you don't get an error at some point? Maybe via the logging, or you can also provide an implementation for the `Error` method on the `Extender`, it will be called for every error encountered.

Martin

**Comment by juliend2** [comment]
Hi Martin,

Thanks for your response. I'm going to try that and get back to you today or tomorrow, to see if there is any error, like you suggested.

Thanks a lot.

Julien

**Comment by juliend2** [comment]
@mna 

I tested your idea:

```
package main

import (
	"fmt"
	"github.com/PuerkitoBio/gocrawl"
	"time"
)

// Create the Extender implementation, based on the gocrawl-provided DefaultExtender,
// because we don't want/need to override all methods.
type ExampleExtender struct {
	gocrawl.DefaultExtender // Will use the default implementation of all but Visit() and Filter()
}

func (this *ExampleExtender) Error(err *gocrawl.CrawlError) {
	fmt.Println("Error: ---------------------------------------")
	fmt.Println(err.Error())
}

func ExampleCrawl(baseUrl string) {
	// Set custom options
	opts := gocrawl.NewOptions(new(ExampleExtender))
	opts.CrawlDelay = 1 * time.Second
	opts.LogFlags = gocrawl.LogAll

	c := gocrawl.NewCrawlerWithOptions(opts)
	c.Run(baseUrl)

}

func (this *ExampleExtender) RequestRobots(ctx *gocrawl.URLContext, robotAgent string) (data []byte, request bool) {
	fmt.Println("Disobey robots")
	return []byte(""), false // as if there was no robots.txt at all to obey
}

func main() {
	opts := gocrawl.NewOptions(new(ExampleExtender))
	opts.CrawlDelay = 1 * time.Second
	opts.LogFlags = gocrawl.LogAll
	c := gocrawl.NewCrawlerWithOptions(opts)
	c.Run("http://subdomain.example.com/")
}
```

But I don't get any error.

**Comment by juliend2** [comment]
Ah ok, I think I understand.

It's because the site I was testing was https. But all the internal links in the site are pointing to the http version (which are redirected to the https version). But then, when gocrawl sees them, it ignores them because they are outside of the provided host (which starts with https).

So I will close this, since it's not an issue with gocrawl, but rather an issue with the site I'm crawling.

Thank you!
