### ISSUE TITLE
Precompile selectors for goquery

### ISSUE THREAD

**Issue by mikefaraponov** [PuerkitoBio/gocrawl#67]
Just propousal, precompile selector such as base[href] using cascadia so you will be able to use FindMatcher

**Comment by mna** [comment]
Hello Mike,

Yes, that makes total sense, there are 2 selectors used by gocrawl that should be pre-compiled indeed. Happy to merge a PR that would change this, if you or anyone else is interested.

Thanks,
Martin

**Comment by mikefaraponov** [comment]
https://github.com/PuerkitoBio/gocrawl/pull/68
