### ISSUE TITLE
Are there have any Translation documents?

### ISSUE THREAD

**Issue by lionking6792** [PuerkitoBio/gocrawl#74]
Hi! I'm looking for some Translation documents, but I might think it doesn't have any translated documents.

Are you have or need translated documents?

I'm Korean and many Korean is looking forward your repository so, it might be helpful to get some translated documents.

As soon as possible, I'll translate some documents and pr to you if you are okay

Thanks for reading :)

**Comment by mna** [comment]
Hello,

I'm not aware of any translation being available, I'd absolutely welcome such documents! Looking forward to your PR.

Thank you,
Martin

**Comment by lionking6792** [comment]
Thanks for comment :)

I'll translate Korean and PR as soon as possible. ( maybe within 2~3weeks ).
I'll work hard and precisely so, I'll looking forward your merge.

Thank you :)
